# Generated by Django 4.1.5 on 2023-01-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_author_book_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='available_books',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=11),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=240),
        ),
    ]
